
const product_data={
    women:[
    {
        id:1,
        name:"Apollo Running Short",
        price:50,
        currency:"$",
        thumb:"./images/short.jfif"
        },
        {
        id:2,
        name:"Apollo Running Short",
        price:50,
        currency:"$",
        thumb:"./images/blouse.jpg"
        },
        {
        id:3,
        name:"Apollo Running Short",
        price:50,
        currency:"$",
        thumb:"./images/jacket.jfif"
        },
        {
        id:4,
        name:"Apollo Running Short",
        price:50,
        currency:"$",
        thumb:"./images/t-shirt.jfif"
        },
    {
        id:5,
        name:"Apollo Running Short",
        price:50,
        currency:"$",
        thumb:"./images/blouse.jpg"
        },
        {
        id:6,
        name:"Apollo Running Short",
        price:50,
        currency:"$",
        thumb:"./images/jacket.jfif"
        },
        {
        id:7,
        name:"Apollo Running Short",
        price:50,
        currency:"$",
        thumb:"./images/short.jfif"
        },
        {
        id:8,
        name:"Apollo Running Short",
        price:50,
        currency:"$",
        thumb:"./images/bag.jpeg"
            }
        ],
    men:[
        {
            id:9,
            name:"Nike",
            price:40,
            currency:"$",
            thumb:"./images/men1.jpg"
            },
            {
            id:10,
            name:"Nike",
            price:40,
            currency:"$",
            thumb:"./images/men2.jpg"
            },
            {
            id:11,
            name:"Nike",
            price:40,
            currency:"$",
            thumb:"./images/men3.webp"
            },
            {
            id:12,
            name:"Nike",
            price:40,
            currency:"$",
            thumb:"./images/men4.jpg"
            },
        {
            id:13,
            name:"Nike",
            price:40,
            currency:"$",
            thumb:"./images/men5.webp"
            },
            {
            id:14,
            name:"Nike",
            price:40,
            currency:"$",
            thumb:"./images/men6.jpg"
            },
            {
            id:15,
            name:"Nike",
            price:40,
            currency:"$",
            thumb:"./images/men7.jpg"
            },
            {
            id:16,
            name:"Nike",
            price:40,
            currency:"$",
            thumb:"./images/men8.jpg"
                }
            ],
    kids:[
    {
            id:17,
            name:"Adidas",
            price:20,
            currency:"$",
            thumb:"./images/kids1.jpg"
            },
            {
            id:18,
            name:"Adidas",
            price:20,
            currency:"$",
            thumb:"./images/kids2.jpg"
            },
            {
            id:19,
            name:"Adidas",
            price:20,
            currency:"$",
            thumb:"./images/kids3.webp"
            },
            {
            id:20,
            name:"Adidas",
            price:20,
            currency:"$",
            thumb:"./images/kids4.jpg"
            },
        {
            id:21,
            name:"Adidas",
            price:20,
            currency:"$",
            thumb:"./images/kids5.png"
            },
            {
            id:22,
            name:"Adidas",
            price:20,
            currency:"$",
            thumb:"./images/kids6.webp"
            },
            {
            id:23,
            name:"Adidas",
            price:20,
            currency:"$",
            thumb:"./images/kids7.webp"
            },
            {
            id:24,
            name:"Adidas",
            price:20,
            currency:"$",
            thumb:"./images/kids8.jpg"
                }
            ]

}
export default product_data;